name: Build and Deploy Iconic Vue PWA

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build app
      run: |
        npm ci
        npm run build
  
    - name: Deploy app
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: prod
        folder: dist
